### ISSUE TITLE
No Bad alcs plugin wont work .

### ISSUE THREAD

**Issue by saim126** [CreativeTechGuy/no-bad-alchs#10] opened 2024-10-29 00:59 UTC
The no bad alcs plugin was workng normally for me a couple days ago and now it doesn't filter any of the items in my inventory. Tried restting it, restarting Runelite, downloading it on a fresh profile, manually deleting it from the .runlite folder. Still not working, Not sure how to proceed. I know it still works for other players so its something on my end. Love the plugin.

**Comment by Felanbird** [comment] 2024-10-29 03:41
Conflict with the `Normal Ancient Teleports` plugin

**Comment by CreativeTechGuy** [comment] 2024-10-29 23:51
@saim126 can you confirm if your issue was fixed by disabling the "Normal Ancient Teleports" plugin? Or any other plugin? Odds are it's a conflict with another plugin and it'd be good to find which one and report it to them.

**Comment by Gimmee1** [comment] 2024-11-04 03:07
> @saim126 can you confirm if your issue was fixed by disabling the "Normal Ancient Teleports" plugin? Or any other plugin? Odds are it's a conflict with another plugin and it'd be good to find which one and report it to them.

I've also been having this issue recently, disabling/uninstalling "Normal Ancient Teleports" was not the solution.

I even went through the trouble of disabling/enabling all of my current plugins to find which one may be root of conflict with NBA but to no avail was there a solution.

**Comment by Gimmee1** [comment] 2024-11-04 03:22
> > @saim126 can you confirm if your issue was fixed by disabling the "Normal Ancient Teleports" plugin? Or any other plugin? Odds are it's a conflict with another plugin and it'd be good to find which one and report it to them.
> 
> I've also been having this issue recently, disabling/uninstalling "Normal Ancient Teleports" was not the solution.
> 
> I even went through the trouble of disabling/enabling all of my current plugins to find which one may be root of conflict with NBA but to no avail was there a solution.

<img width="595" alt="NBA" src="https://github.com/user-attachments/assets/46d5f517-126b-4fa9-96ad-c1757bb405d4">

**Comment by CreativeTechGuy** [comment] 2024-11-04 04:09
Hmm I'm not sure. The only thing I can think, does it work in Fixed display mode? Maybe something broke in Resizable or one of the other UI modes?

**Comment by Gimmee1** [comment] 2024-11-04 05:40
> Hmm I'm not sure. The only thing I can think, does it work in Fixed display mode? Maybe something broke in Resizable or one of the other UI modes?

Just tried both Fixed Classic and Resizable Modern, no bueno

**Comment by CreativeTechGuy** [comment] 2024-11-04 05:53
I haven't played in a while but just logged back in to test this out since I want to make sure this works for everyone. I cannot seem to reproduce it, even with the same configuration you are using. I'm not sure where to go from here unfortunately...

Maybe it's something with your account, with some other plugin conflicting, with some runelite setting (not a PluginHub plugin), it's really hard to say without being able to see it and debug.

**Comment by Gimmee1** [comment] 2024-11-04 18:06
I ended up turning all plugins off with only NBA on and it is now working properly. I also enabled each default plugin one by one to see if one of them was causing the problem but they were not. For future-proofing I just made an "All Off" profile on RuneLite to help stabilize any plugins that may be having issues of this magnitude.

Thank you for your time and plugin creation @CreativeTechGuy !

**Comment by Felanbird** [comment] 2024-11-05 05:33
It's Normal Ancient Teleports, you just can't disable it, you must restart the client after you do. It's absolutely not the default Spellbook plugin

**Comment by saim126** [comment] 2024-11-07 21:50
yeah, found out it was the ancient tele plugin

**Comment by CreativeTechGuy** [comment] 2024-11-09 05:03
@saim126 if you haven't already, can you please submit a but report to the "Normal Ancient Teleports" plugin repo? I'll be closing this issue as it's not an issue with this plugin.

**Closed by CreativeTechGuy** 2024-11-09 05:03 UTC
